//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Student
{
    public partial class Courses
    {
    protected global::System.Web.UI.WebControls.TextBox txtEnrollmentKey;
    protected global::System.Web.UI.WebControls.Label lblEnrollCourseName;
    protected global::System.Web.UI.WebControls.Button btnSubmitEnrollment;
    protected global::System.Web.UI.WebControls.GridView gvCourses;
    protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}
