//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Student
{
    public partial class Quizzes
    {
        protected global::System.Web.UI.WebControls.GridView gvQuizzes;
        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}
