//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Admin
{
    public partial class CourseDetails
    {
        protected global::System.Web.UI.ScriptManager ScriptManager1;

        protected global::System.Web.UI.WebControls.Label lblCourseTitle;

        protected global::System.Web.UI.WebControls.Label lblTeacherName;

        protected global::System.Web.UI.WebControls.Label lblEnrollmentCode;

        protected global::System.Web.UI.WebControls.Button btnEditCourse;

        protected global::System.Web.UI.WebControls.Button btnBackToCourses;

        protected global::System.Web.UI.WebControls.Label lblCourseDescription;

        protected global::System.Web.UI.WebControls.Label lblTotalStudents;

        protected global::System.Web.UI.WebControls.Label lblTotalAssignments;

        protected global::System.Web.UI.WebControls.Label lblTotalQuizzes;

        protected global::System.Web.UI.WebControls.Label lblAvgGrade;

        protected global::System.Web.UI.WebControls.Button btnAddStudent;

        protected global::System.Web.UI.UpdatePanel upStudents;

        protected global::System.Web.UI.WebControls.Repeater rptStudents;

        protected global::System.Web.UI.WebControls.Panel pnlNoStudents;

        protected global::System.Web.UI.UpdatePanel upEditCourse;

        protected global::System.Web.UI.WebControls.TextBox txtEditTitle;

        protected global::System.Web.UI.WebControls.DropDownList ddlEditTeacher;

        protected global::System.Web.UI.WebControls.TextBox txtEditEnrollmentCode;

        protected global::System.Web.UI.WebControls.TextBox txtEditDescription;

        protected global::System.Web.UI.WebControls.Label lblEditError;

        protected global::System.Web.UI.WebControls.Button btnUpdateCourse;

        protected global::System.Web.UI.UpdatePanel upAddStudent;

        protected global::System.Web.UI.WebControls.Label lblStudentSearch;

        protected global::System.Web.UI.WebControls.TextBox txtStudentSearch;

        protected global::System.Web.UI.WebControls.Label lblAvailableStudents;

        protected global::System.Web.UI.WebControls.ListBox lstAvailableStudents;

        protected global::System.Web.UI.WebControls.Label lblAddStudentError;

        protected global::System.Web.UI.WebControls.Label lblAddStudentSuccess;

        protected global::System.Web.UI.WebControls.Button btnEnrollStudents;

        protected global::System.Web.UI.UpdatePanel upStudentProgress;

        protected global::System.Web.UI.WebControls.Label lblStudentName;

        protected global::System.Web.UI.WebControls.Label lblStudentEmail;

        protected global::System.Web.UI.WebControls.Label lblEnrollmentDate;

        protected global::System.Web.UI.WebControls.Label lblAssignmentsCompleted;

        protected global::System.Web.UI.WebControls.Label lblQuizzesCompleted;

        protected global::System.Web.UI.WebControls.Label lblAverageGrade;

        protected global::System.Web.UI.WebControls.Repeater rptStudentActivity;

        protected global::System.Web.UI.WebControls.Panel pnlNoActivity;

        protected global::System.Web.UI.WebControls.Label lblEditTitle;

        protected global::System.Web.UI.WebControls.Label lblEditTeacher;

        protected global::System.Web.UI.WebControls.Label lblEditEnrollmentCode;

        protected global::System.Web.UI.UpdatePanel upHeaderButtons;

        protected global::System.Web.UI.UpdatePanel upAddStudentButton;

        protected global::System.Web.UI.UpdatePanel upStudentActions;

        protected global::System.Web.UI.UpdatePanel upEditModalFooter;

        protected global::System.Web.UI.UpdatePanel upAddStudentModalFooter;
    }
}