//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Admin
{


    public partial class Dashboard
    {
        protected global::System.Web.UI.WebControls.Label lblTotalEnrollments;

        protected global::System.Web.UI.WebControls.Label lblTotalUsers;

        protected global::System.Web.UI.WebControls.Label lblActiveCourses;

    }
}
