//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Admin
{


    public partial class Settings
    {
        protected global::System.Web.UI.WebControls.TextBox txtAdminEmail;
        protected global::System.Web.UI.WebControls.TextBox txtOldPassword;
        protected global::System.Web.UI.WebControls.TextBox txtNewPassword;
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;
        protected global::System.Web.UI.WebControls.TextBox txtSiteName;
        protected global::System.Web.UI.WebControls.Label lblStatus;
        protected global::System.Web.UI.WebControls.Label lblSettingsMessage;
        protected global::System.Web.UI.WebControls.Button btnSave;
    }
}
