//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Admin
{


    public partial class Users
    {
        /// <summary>
        /// gvUsers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvUsers;

        /// <summary>
        /// txtSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSearch;

        /// <summary>
        /// ddlRoleFilter control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlRoleFilter;

        /// <summary>
        /// lblTotalUsers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalUsers;

        /// <summary>
        /// lblTotalTeachers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalTeachers;

        /// <summary>
        /// lblTotalStudents control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalStudents;

        /// <summary>
        /// txtAddFullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAddFullName;

        /// <summary>
        /// txtAddEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAddEmail;

        /// <summary>
        /// txtAddUsername control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAddUsername;

        /// <summary>
        /// txtAddPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAddPassword;

        /// <summary>
        /// ddlAddRole control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlAddRole;

        /// <summary>
        /// lblAddUserError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblAddUserError;

        /// <summary>
        /// lblFullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblFullName;

        /// <summary>
        /// lblEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblEmail;

        /// <summary>
        /// lblUsername control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblUsername;

        /// <summary>
        /// lblPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPassword;

        /// <summary>
        /// lblRole control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblRole;

        /// <summary>
        /// rfvFullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvFullName;

        /// <summary>
        /// rfvEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEmail;

        /// <summary>
        /// rfvUsername control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvUsername;

        /// <summary>
        /// rfvPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPassword;

        /// <summary>
        /// rfvRole control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvRole;

        /// <summary>
        /// revEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revEmail;

        /// <summary>
        /// revPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revPassword;

        /// <summary>
        /// btnSaveUser control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSaveUser;

        /// <summary>
        /// txtEditFullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEditFullName;

        /// <summary>
        /// txtEditEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEditEmail;

        /// <summary>
        /// txtEditUsername control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEditUsername;

        /// <summary>
        /// txtEditPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEditPassword;

        /// <summary>
        /// ddlEditRole control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlEditRole;

        /// <summary>
        /// lblEditUserError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblEditUserError;

        /// <summary>
        /// lblEditFullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblEditFullName;

        /// <summary>
        /// lblEditEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblEditEmail;

        /// <summary>
        /// lblEditUsername control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblEditUsername;

        /// <summary>
        /// lblEditPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblEditPassword;

        /// <summary>
        /// lblEditRole control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblEditRole;

        /// <summary>
        /// btnUpdateUser control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnUpdateUser;

        /// <summary>
        /// btnConfirmDeleteUser control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConfirmDeleteUser;

        /// <summary>
        /// lblDeleteUserError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblDeleteUserError;
    }
}
