//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Teacher
{


    public partial class Assignments
    {
        protected global::System.Web.UI.WebControls.GridView gvAssignments;
        protected global::System.Web.UI.WebControls.TextBox txtAddTitle;
    protected global::System.Web.UI.WebControls.TextBox txtAddDescription;
        protected global::System.Web.UI.WebControls.TextBox txtAddDueDate;
        protected global::System.Web.UI.WebControls.Button btnSaveAssignment;
        protected global::System.Web.UI.WebControls.TextBox txtEditTitle;
    protected global::System.Web.UI.WebControls.TextBox txtEditDescription;
        protected global::System.Web.UI.WebControls.TextBox txtEditDueDate;
        protected global::System.Web.UI.WebControls.Button btnUpdateAssignment;
    protected global::System.Web.UI.UpdatePanel UpdatePanel1;
    }
}
