//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Teacher
{


    public partial class AssignmentSubmitted
    {
    protected global::System.Web.UI.WebControls.GridView gvSubmittedAssignments;
    protected global::System.Web.UI.WebControls.Label lblMessage;
    protected global::System.Web.UI.WebControls.TextBox txtGrade;
    protected global::System.Web.UI.WebControls.TextBox txtScore;
    protected global::System.Web.UI.WebControls.TextBox txtFeedback;
    protected global::System.Web.UI.WebControls.HiddenField hfSubmissionId;
    protected global::System.Web.UI.WebControls.Button btnSaveGrade;
    }
}
