//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Teacher
{


    public partial class Courses
    {
    protected global::System.Web.UI.WebControls.GridView gvTeacherCourses;
    protected global::System.Web.UI.WebControls.TextBox txtEditEnrollmentCode;
    protected global::System.Web.UI.WebControls.Label lblEditEnrollmentError;
    }
}
