//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Teacher
{
    public partial class Questions
    {
        protected global::System.Web.UI.WebControls.GridView gvQuestions;
        protected global::System.Web.UI.WebControls.TextBox txtAddQuestionText;
        protected global::System.Web.UI.WebControls.DropDownList ddlAddQuestionType;
        protected global::System.Web.UI.WebControls.Button btnSaveQuestion;
        protected global::System.Web.UI.WebControls.TextBox txtEditQuestionText;
        protected global::System.Web.UI.WebControls.DropDownList ddlEditQuestionType;
        protected global::System.Web.UI.WebControls.Button btnUpdateQuestion;
        protected global::System.Web.UI.UpdatePanel UpdatePanel1;
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        protected global::System.Web.UI.WebControls.TextBox txtAddOptionA;
        protected global::System.Web.UI.WebControls.TextBox txtAddOptionB;
        protected global::System.Web.UI.WebControls.TextBox txtAddOptionC;
        protected global::System.Web.UI.WebControls.TextBox txtAddOptionD;
        protected global::System.Web.UI.WebControls.DropDownList ddlAddCorrectOption;
        protected global::System.Web.UI.WebControls.TextBox txtEditOptionA;
        protected global::System.Web.UI.WebControls.TextBox txtEditOptionB;
        protected global::System.Web.UI.WebControls.TextBox txtEditOptionC;
        protected global::System.Web.UI.WebControls.TextBox txtEditOptionD;
        protected global::System.Web.UI.WebControls.DropDownList ddlEditCorrectOption;
    }
}
