//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Teacher
{


    public partial class Quizzes
    {
        protected global::System.Web.UI.WebControls.GridView gvQuizzes;
        protected global::System.Web.UI.WebControls.TextBox txtAddQuizTitle;
        protected global::System.Web.UI.WebControls.TextBox txtAddQuizDescription;
        protected global::System.Web.UI.WebControls.TextBox txtAddQuizDueDate;
        protected global::System.Web.UI.WebControls.Button btnSaveQuiz;
        protected global::System.Web.UI.WebControls.TextBox txtEditQuizTitle;
        protected global::System.Web.UI.WebControls.TextBox txtEditQuizDescription;
        protected global::System.Web.UI.WebControls.TextBox txtEditQuizDueDate;
        protected global::System.Web.UI.WebControls.Button btnUpdateQuiz;
    }
}
